---
title: "Cleaning Seed Dispersal Camera data"
author: "Camila Vargas"
date: "1/25/2022"
output: html_document
---

## Set up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## Load packages
library(here)
library(tidyverse)
library(janitor)
library(readxl)
library(freeR)

## Sets R not to use scientific notations
options(scipen=999) 

```

## Exploring data
```{r}

excel_sheets(here::here("6.raw_data/Seed dispersal camera data.xls"))

```

21 sheets found. According to Alex we only need "refined data".

## Read data
```{r}
capture_palat_raw <- read_excel(here::here("6.raw_data/Seed dispersal camera data.xls"), sheet = "refined data") %>% 
  clean_names()
```


## Checking data
```{r}
colnames(capture_palat_raw)
str(capture_palat_raw)

unique(capture_palat_raw$day_night)
sort(unique(capture_palat_raw$experimental_unit))
sort(unique(capture_palat_raw$native_invasive))
unique(capture_palat_raw$treatment)
unique(capture_palat_raw$seed_seedling)
sort(unique(capture_palat_raw$disperser))
unique(capture_palat_raw$land_crab_rat)
unique(capture_palat_raw$sex)
unique(capture_palat_raw$age)
unique(capture_palat_raw$event_time) ## there is one * that makes the column not be numeric
unique(capture_palat_raw$time_from_start_hr) ## there is one * that makes the column not be numeric
unique(capture_palat_raw$disperser_action)
unique(capture_palat_raw$diaspore_fate)
unique(capture_palat_raw$reference_plot_fate)
sort(unique(capture_palat_raw$notes))

complete(capture_palat_raw)

```

Ask id * = NA and then update each column with * and save to clean_data again

## Save
```{r}
write_csv(capture_palat_raw, here::here("7.clean_data/Palmyra_seed_dispersal_camera_2005.csv"))

```


